# Header
menu:
  捐助我: https://afdian.net/@emptydreams
  哔哩哔哩: https://space.bilibili.com/66951474
  GitHub: https://github.com/EmptyDreams

# Content
excerpt_link: 更多内容
prev: 上一页
next: 下一页
#reply: 评论
#share: 分享
fancybox: true

# Sidebar
widgets:
#- about
#- support
#- gzh
#- music
#- ad
- recent_posts
- archive
- category
- tagcloud
#- link
#- account
- script

# Miscellaneous
google_analytics:
duoshuo_shortname: flhexo
#rss: /atom.xml
favicon: https://blog.emptydreams.xyz/logo.png
#google_site_verification: NCXVSqxqB-os803-VFMtIEd1SUNJVOIjctCfNYUwD0w
#baidu_site_verification: Nzwx7HuplM
#bing_site_verification: 9E9EA92F7E5327E1FE8A5196D5253664
#music: